[package]
name = "semver-sort"
version = "1.1.0"
authors = ["Chris Dickinson <christopher.s.dickinson@gmail.com>"]
edition = "2018"
license = "MIT"



[dependencies]
structopt = "0.3.20"
semver = "0.11.0"
